### ISSUE TITLE
There is crash on API 22x on Android 

### ISSUE THREAD

**Issue by Mookker** [alexrainman/MvvmCross.FlyOutMenu#1]
AppCompat does not support the current theme features exception while calling 
        public override void SetContentView(View view, ViewGroup.LayoutParams @params)
        {
            base.SetContentView(view, @params);
            _helper.RegisterAboveContentView(view, @params);
        }

**Comment by alexrainman** [comment]
Already fixed this. Will update soon.

**Comment by Mookker** [comment]
Thank you!

**Comment by alexrainman** [comment]
Updated. Now SlidingMenuSharp reference the project itself. You need to download it.

**Comment by alexrainman** [comment]
>fixed
