### ISSUE TITLE
Question : how do you navigate between view?

### ISSUE THREAD

**Issue by paddyfink** [alexrainman/MvvmCross.FlyOutMenu#2]
Hello alex,

I would like to know how do you navigate between screen? It will be nice if you could add 2 screens with a item for each screen in the menu and show how the navigation works.  Thx

**Comment by alexrainman** [comment]
Will do.

**Comment by paddyfink** [comment]
you the man ;-).  In the meantime, could you show me an example of code? I'm kind of stuck in a development task. Thanks again

**Comment by alexrainman** [comment]
As soon as i get to the office :)

**Comment by paddyfink** [comment]
I ended up using a custom presenter like here : http://stackoverflow.com/questions/27613707/has-anyone-gotten-xamarin-sidebar-mvvmcross-storyboards-to-work-together

Works like a charm.

**Comment by alexrainman** [comment]
I have it working with storyboards too :) Sorry, i had a crazy day. I will update it with some content and navigation. Thanks for using it.

**Comment by alexrainman** [comment]
And, i will add Material Design in Android.

**Comment by jesussaad** [comment]
Could you provide this sample Alex?
